# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ca5322df6679496fb9d868c4d0909c3276a4cd98e8037353c9d2423b2c5696263dd61723765621de64be887ae67568b3bf5a93f7b5c3497a409ff47739907e

test:
  secret_key_base: 13e060f969a83e947bf301dae409698208425cb77c431202c5240686bec12ec6556c2072bbb48f63402c46c4cefd89cbc599fb74c46a445726b67783b013c4c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
